AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 Instance with Security Group

Resources:

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0e38835daf6b8a2b9
      SecurityGroupIds:
        - !Ref MySecurityGroup